# Generated by Django 6.0.4 on 2026-04-15 13:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_id', models.IntegerField(unique=True)),
                ('dep_name', models.CharField(choices=[('ECE', 'ece'), ('CSE', 'cse'), ('CIVIL', 'civil'), ('MECH', 'mech'), ('AI&DS', 'ai&ds'), ('EEE', 'eee')], default='CSE', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_id', models.IntegerField(unique=True)),
                ('std_name', models.CharField(max_length=30)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.department')),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.IntegerField(unique=True)),
                ('teacher_name', models.CharField(max_length=20)),
                ('teacher_mobile', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[6-9]{1}[0-9]{9}', message='Enter a valid 10-digit mobile number starting with 6-9')])),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.department')),
            ],
        ),
    ]
